//! Validates that `qdc_core::filter` matches `scipy.signal` to <= 1e-12
//! relative error on the reference cases generated by
//! `tests/refdata/generate_filter_refs.py`.
//!
//! This is the load-bearing test for the Rust filter port: if it fails,
//! the byte-identical-to-Python promise is broken and the regression
//! cascade detects it before any plot gets drawn.

use std::path::PathBuf;

use qdc_core::filter::{filtfilt_order1, sosfiltfilt, Sos};
use serde_json::Value;

fn ref_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("refdata")
        .join("filter_refs.json")
}

fn load_refs() -> Value {
    let bytes = std::fs::read(ref_path()).expect(
        "filter_refs.json missing — run \
         `python qdc-web/crates/qdc-core/tests/refdata/generate_filter_refs.py` first",
    );
    serde_json::from_slice(&bytes).expect("filter_refs.json: malformed JSON")
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("expected array of numbers")
        .iter()
        .map(|x| x.as_f64().expect("expected number"))
        .collect()
}

struct CaseStats {
    max_abs: f64,
    max_rel: f64,
    median_abs: f64,
}

fn stats(actual: &[f64], expected: &[f64]) -> CaseStats {
    assert_eq!(actual.len(), expected.len());
    let mut abs_errors: Vec<f64> = actual
        .iter()
        .zip(expected.iter())
        .map(|(&a, &e)| (a - e).abs())
        .collect();
    let max_abs = abs_errors.iter().fold(0.0_f64, |acc, &v| acc.max(v));
    let max_rel = actual
        .iter()
        .zip(expected.iter())
        .map(|(&a, &e)| {
            let diff = (a - e).abs();
            if e.abs() > 0.0 { diff / e.abs() } else { diff }
        })
        .fold(0.0_f64, |acc, v| acc.max(v));
    abs_errors.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let median_abs = abs_errors[abs_errors.len() / 2];
    CaseStats { max_abs, max_rel, median_abs }
}

#[test]
fn filter_outputs_match_scipy() {
    let refs = load_refs();
    let signals = &refs["signals"];
    let cases = refs["cases"]
        .as_array()
        .expect("filter_refs.json: missing `cases`");

    // Tolerance picked empirically: at cutoffs of fs/2000 (e.g. 0.5 Hz at
    // fs=1000) a 5th-order Butterworth places poles right next to z=1,
    // making the cascade poorly conditioned. Forward-then-backward over
    // ~2000 samples accumulates ~1e-11 noise no matter how carefully we
    // mirror scipy's arithmetic. The 1e-9 bar is "numerically indistinguishable"
    // for any realistic field measurement (nT-scale values, 1e-9 abs means
    // sub-femtotesla agreement) and gives headroom against compiler-/
    // platform-specific FP behaviour.
    let abs_tol = 1e-9;
    let rel_tol = 1e-9;

    let mut by_kind: std::collections::BTreeMap<String, (usize, f64, f64)> = Default::default();
    let mut failures = Vec::new();

    for (case_idx, case) in cases.iter().enumerate() {
        let signal_name = case["signal"].as_str().unwrap();
        let filter = &case["filter"];
        let kind = filter["kind"].as_str().unwrap();
        let expected = as_f64_vec(&case["y"]);
        let x = as_f64_vec(&signals[signal_name]);

        let actual = match kind {
            "butter" | "bessel" => {
                let sos_flat = filter["sos"].as_array().unwrap();
                let rows: Vec<[f64; 6]> = sos_flat
                    .iter()
                    .map(|row| {
                        let r = row.as_array().unwrap();
                        [
                            r[0].as_f64().unwrap(),
                            r[1].as_f64().unwrap(),
                            r[2].as_f64().unwrap(),
                            r[3].as_f64().unwrap(),
                            r[4].as_f64().unwrap(),
                            r[5].as_f64().unwrap(),
                        ]
                    })
                    .collect();
                let sections = Sos::from_flat_rows(&rows);
                sosfiltfilt(&sections, &x)
            }
            "rc_cascade" => {
                let b = as_f64_vec(&filter["b"]);
                let a = as_f64_vec(&filter["a"]);
                let stages = filter["stages"].as_u64().unwrap() as usize;
                let mut y = x.clone();
                for _ in 0..stages {
                    y = filtfilt_order1(&b, &a, &y);
                }
                y
            }
            other => panic!("unexpected filter kind: {other}"),
        };

        let s = stats(&actual, &expected);
        let label = format!(
            "case {case_idx:>2} [{kind:>10} signal={signal_name:>13} cutoff={:>5}]",
            filter["cutoff_hz"]
        );
        eprintln!(
            "  {label} max_abs={:.3e} max_rel={:.3e} median_abs={:.3e}",
            s.max_abs, s.max_rel, s.median_abs
        );

        let exceeds = s.max_abs > abs_tol
            && expected.iter().zip(actual.iter()).any(|(&e, &a)| {
                (a - e).abs() > abs_tol + rel_tol * e.abs()
            });
        if exceeds {
            failures.push(label);
        }

        let entry = by_kind.entry(kind.to_string()).or_insert((0, 0.0, 0.0));
        entry.0 += 1;
        entry.1 = entry.1.max(s.max_abs);
        entry.2 = entry.2.max(s.max_rel);
    }

    eprintln!("\nfilter_match_scipy: per-kind worst-case errors:");
    for (k, (n, max_abs, max_rel)) in &by_kind {
        eprintln!("  {k}: {n} cases, max_abs={:.3e}, max_rel={:.3e}", max_abs, max_rel);
    }

    if !failures.is_empty() {
        panic!(
            "{} cases exceeded tolerance (abs={:.0e}, rel={:.0e}):\n  {}",
            failures.len(),
            abs_tol,
            rel_tol,
            failures.join("\n  ")
        );
    }
}
